services:
  kafka:
    image: quay.io/ogunalp/kafka-native
    hostname: broker1
    container_name: broker1
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:9092
      SERVER_HOST: broker1
      KAFKA_BROKER_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker1:9094
  namenode:
    build: ./hdfs/
    volumes:
    - ./hdfs/namenode/:/etc/hadoop
    environment:
      HADOOP_CONF_DIR: /etc/hadoop
    command: ["/etc/hadoop/entry.sh"]
  datanode:
    build: ./hdfs/
    volumes:
    - ./hdfs/datanode/:/etc/hadoop
    environment:
      HADOOP_CONF_DIR: /etc/hadoop
    command: ["/etc/hadoop/entry.sh"]
  jobmanager:
    build: ./flink/
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
    - ./flink/hadoop/:/etc/hadoop
    environment:
      - HADOOP_USER_NAME=root
      - HADOOP_CONF_DIR=/etc/hadoop
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        
        state.checkpoints.dir: hdfs:///checkpoints/
  taskmanager:
    build: ./flink/
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 2
    volumes:
    - ./flink/hadoop/:/etc/hadoop
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop
      - HADOOP_USER_NAME=root
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2        
        state.checkpoints.dir: hdfs:///checkpoints/
